### ISSUE TITLE
NoSuchElementException: Collection contains no element matching the predicate.

### ISSUE THREAD

**Issue by SrBedrock** [OneLiteFeatherNET/Attollo#18]
### Expected behavior

No erros on console.

### Actual behavior

Erros on console:

```
[13:43:56 ERROR]: Could not pass event PlayerToggleSneakEvent to Attollo v1.0.1
java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at dev.themeinerlp.attollo.listener.AttolloListener.handleElevator(AttolloListener.kt:72) ~[Attollo-1.0.1-all.jar:?]
        at dev.themeinerlp.attollo.listener.AttolloListener.handleElevator$default(AttolloListener.kt:29) ~[Attollo-1.0.1-all.jar:?]
        at dev.themeinerlp.attollo.listener.AttolloListener.onDown(AttolloListener.kt:26) ~[Attollo-1.0.1-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor74.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-521]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-521]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-521]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerCommand(ServerGamePacketListenerImpl.java:2631) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-521]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-521]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-521]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-521]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-521]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-521]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-521]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-521]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps to reproduce

Crouch or jump when there is no longer an elevator block above or below you.

### Plugin and Datapack List

```
[13:45:57 INFO]: Server Plugins (12):
[13:45:57 INFO]: Bukkit Plugins:
[13:45:57 INFO]:  - Attollo, Essentials, EssentialsSpawn, LuckPerms, Multiverse-Core, PlaceholderAPI, ProtocolLib, spark, Vault, ViaBackwards
[13:45:57 INFO]:  ViaVersion, VoidGen
```

### Paper version

```
[13:42:57 INFO]: Checking version, please wait...
[13:42:58 INFO]: This server is running Paper version git-Paper-521 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcec5b1)
You are running the latest version
Previous version: git-Paper-519 (MC: 1.19.4)
```

### Plugin version

```
[13:43:30 INFO]: Attollo version 1.0.1
[13:43:30 INFO]: Author: TheMeinerLP
```

**Comment by TheMeinerLP** [comment]
Thanks for reporting. I will look into it

**Comment by TheMeinerLP** [comment]
I can't replicated it. Can you try the new version from Hangar ?
https://hangar.papermc.io/OneLiteFeather/Attollo/versions/1.0.2-SNAPSHOT+297da9c
